// Generated by gencpp from file rgbd_filter/CustomArray.msg
// DO NOT EDIT!


#ifndef RGBD_FILTER_MESSAGE_CUSTOMARRAY_H
#define RGBD_FILTER_MESSAGE_CUSTOMARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rgbd_filter
{
template <class ContainerAllocator>
struct CustomArray_
{
  typedef CustomArray_<ContainerAllocator> Type;

  CustomArray_()
    : array()  {
    }
  CustomArray_(const ContainerAllocator& _alloc)
    : array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _array_type;
  _array_type array;





  typedef boost::shared_ptr< ::rgbd_filter::CustomArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgbd_filter::CustomArray_<ContainerAllocator> const> ConstPtr;

}; // struct CustomArray_

typedef ::rgbd_filter::CustomArray_<std::allocator<void> > CustomArray;

typedef boost::shared_ptr< ::rgbd_filter::CustomArray > CustomArrayPtr;
typedef boost::shared_ptr< ::rgbd_filter::CustomArray const> CustomArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rgbd_filter::CustomArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rgbd_filter::CustomArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rgbd_filter::CustomArray_<ContainerAllocator1> & lhs, const ::rgbd_filter::CustomArray_<ContainerAllocator2> & rhs)
{
  return lhs.array == rhs.array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rgbd_filter::CustomArray_<ContainerAllocator1> & lhs, const ::rgbd_filter::CustomArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rgbd_filter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rgbd_filter::CustomArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rgbd_filter::CustomArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgbd_filter::CustomArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgbd_filter::CustomArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgbd_filter::CustomArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgbd_filter::CustomArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rgbd_filter::CustomArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71f1005c81b671681646a574c6360c24";
  }

  static const char* value(const ::rgbd_filter::CustomArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71f1005c81b67168ULL;
  static const uint64_t static_value2 = 0x1646a574c6360c24ULL;
};

template<class ContainerAllocator>
struct DataType< ::rgbd_filter::CustomArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rgbd_filter/CustomArray";
  }

  static const char* value(const ::rgbd_filter::CustomArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rgbd_filter::CustomArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] array\n"
;
  }

  static const char* value(const ::rgbd_filter::CustomArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rgbd_filter::CustomArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rgbd_filter::CustomArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rgbd_filter::CustomArray_<ContainerAllocator>& v)
  {
    s << indent << "array[]" << std::endl;
    for (size_t i = 0; i < v.array.size(); ++i)
    {
      s << indent << "  array[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RGBD_FILTER_MESSAGE_CUSTOMARRAY_H
